export const  REGISTER_REQUEST= 'USERS_REGISTER_REQUEST';
export const  REGISTER_SUCCESS='USERS_REGISTER_SUCCESS';
export const  REGISTER_FAILURE='USERS_REGISTER_FAILURE';


export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SAVE_TOKEN = "SAVE_TOKEN";
export const DELETE_TOKEN = "DELETE_TOKEN" ;
export const LOGGED_OUT="LOGGED_OUT";
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const LOGOUT= 'USERS_LOGOUT';